"""Policy intervention — FROZEN pipeline semantics.

Matches Paper1 pipeline lines 756-763 (action_scaler) and the inline
policy block (lines 1155-1180).

The intervention is applied on a *fixed set of probe states*. The new
action is computed by scaling the original action and clipping to the
action bounds. The treatment target y is generated by re-simulating
the environment with the new action.
"""
from __future__ import annotations

import numpy as np

SPEC_CONFIG = {
    'Hopper-v5':   {'nq': 6, 'nv': 6, 'qpos_tail_len': 5, 'qvel_slice': (5, 11)},
    'Walker2d-v5': {'nq': 9, 'nv': 9, 'qpos_tail_len': 8, 'qvel_slice': (8, 17)},
}


def action_scaler(
    scale: float,
    action_low: np.ndarray,
    action_high: np.ndarray,
):
    """Return a callable that scales actions and clips to bounds."""
    def transform(a: np.ndarray) -> np.ndarray:
        return np.clip(a * scale, action_low, action_high)
    return transform


def _reconstruct_state(obs_row: np.ndarray, spec_id: str):
    cfg = SPEC_CONFIG[spec_id]
    qpos = np.zeros(cfg['nq'], dtype=np.float64)
    qvel = np.zeros(cfg['nv'], dtype=np.float64)
    n = cfg['qpos_tail_len']
    qpos[1:] = obs_row[:n]
    qvel[:] = obs_row[cfg['qvel_slice'][0]:cfg['qvel_slice'][1]]
    return qpos, qvel


def resimulate_with_new_action(
    env,
    probe_obs: np.ndarray,
    new_act: np.ndarray,
):
    """Return new next observations under the transformed actions.

    The probe states are reconstructed from the observations; x position
    is set to 0 (not present in Hopper/Walker2d observations).
    """
    spec_id = env.spec.id
    if spec_id not in SPEC_CONFIG:
        raise ValueError(f'Unsupported environment for policy intervention: {spec_id}')

    new_y_list = []
    for o, a in zip(probe_obs, new_act):
        qpos, qvel = _reconstruct_state(o, spec_id)
        env.unwrapped.set_state(qpos, qvel)
        next_obs, _, _, _, _ = env.unwrapped.step(a.astype(np.float32))
        new_y_list.append(np.asarray(next_obs, dtype=np.float32))
    return np.stack(new_y_list, axis=0)
